name: indie.stunfest.fr

# Code
exclude: ['_raws', '.gitignore', 'Gemfile*']

# Permalink format (without day)
permalink: /:title

# Pagination
paginate_path: ':num'
paginate: 500

# Markdown formatter
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
